/*** Function for checking existence of location in table ***/
CREATE OR REPLACE FUNCTION LOCATION_CHECKER(DIS IN VARCHAR2, THAN IN VARCHAR2)
RETURN NUMBER IS
		CNT NUMBER;
BEGIN
		SELECT COUNT(*) INTO CNT
		FROM LOCATIONS
		WHERE DISTRICT = DIS
		AND THANA = THAN;
		
		IF CNT = 0 THEN
				INSERT INTO LOCATIONS VALUES(LOCATION_ID_GENERATOR.NEXTVAL, DIS, THAN);
				COMMIT;
		END IF;
		
		SELECT MIN(LOCATION_ID) INTO CNT
		FROM LOCATIONS
		WHERE DISTRICT = DIS
		AND THANA = THAN
        GROUP BY DISTRICT, THANA;
		
		RETURN CNT;
END;
/