/*** Sequence for User ID ***/
CREATE SEQUENCE USERID_GENERATOR
INCREMENT BY 1
START WITH 1001;

/*** Sequence for Location ID ***/
CREATE SEQUENCE LOCATION_ID_GENERATOR
INCREMENT BY 1
START WITH 1001;