/*** Storing deleted user credentials ***/
CREATE OR REPLACE TRIGGER USER_DELETED
AFTER DELETE
ON USERS
FOR EACH ROW
DECLARE
BEGIN
		INSERT INTO DELETED_USER VALUES(:OLD.USERID, :OLD.NAME, :OLD.EMAIL_ID);
END;
/

