/*** Storing deleted user credentials ***/
CREATE OR REPLACE TRIGGER USER_DELETED
AFTER DELETE
ON USERS
FOR EACH ROW
DECLARE
BEGIN
		INSERT INTO DELETED_USER VALUES(:OLD.USERID, :OLD.NAME, :OLD.EMAIL_ID);
END;
/

/*** Consistent deleting ***/
CREATE OR REPLACE TRIGGER CONSISTENT_DELETE
AFTER DELETE
ON USERS
FOR EACH ROW
DECLARE
BEGIN
		DELETE FROM EDUCATIONS
		WHERE USERID = :OLD.USERID;
		DELETE FROM OCCUPATIONS
		WHERE USERID = :OLD.USERID;
		DELETE FROM HOBBIES
		WHERE USERID = :OLD.USERID;
		DELETE FROM PARTNER_PREFERENCE
		WHERE USERID = :OLD.USERID;
		DELETE FROM REQUESTS
		WHERE SENDER = :OLD.USERID
		OR RECEIVER = :OLD.USERID;
		DELETE FROM FAILED_LOGIN_COUNTS
		WHERE USERID = :OLD.USERID;
END;
/

/*** Initial preference trigger ***/
CREATE OR REPLACE TRIGGER PREFERENCE_INITIATION
AFTER INSERT
ON USERS
FOR EACH ROW
DECLARE
DECLARE
	GEN CHAR(1);
	DIS VARCHAR2(100);
	OCCU VARCHAR2(100);
	LEV VARCHAR2(100);
	INST VARCHAR2(100);
	H1 VARCHAR2(100);
	H2 VARCHAR2(100);
	H3 VARCHAR2(100);
	H4 VARCHAR2(100);
	H5 VARCHAR2(100);
BEGIN
		IF :NEW.GENDER = 'M' THEN
				GEN := 'F';
		ELSE
				GEN := 'M';
		END IF;
		SELECT DISTRICT INTO DIS FROM LOCATIONS WHERE LOCATION_ID = :NEW.LOCATION_ID;
		SELECT JOB_TITLE INTO OCCU FROM OCCUPATIONS WHERE USERID = :NEW.USERID;
		SELECT EDUCATION_LEVEL INTO LEV FROM EDUCATIONS WHERE USERID = :NEW.USERID;
		SELECT INSTITUTION INTO INST FROM EDUCATIONS WHERE USERID = :NEW.USERID;
		SELECT HOBBY_1 INTO H1 FROM HOBBIES WHERE USERID = :NEW.USERID;
		SELECT HOBBY_2 INTO H2 FROM HOBBIES WHERE USERID = :NEW.USERID;
		SELECT HOBBY_3 INTO H3 FROM HOBBIES WHERE USERID = :NEW.USERID;
		SELECT HOBBY_4 INTO H4 FROM HOBBIES WHERE USERID = :NEW.USERID;
		SELECT HOBBY_5 INTO H5 FROM HOBBIES WHERE USERID = :NEW.USERID;
		INSERT INTO PARTNER_PREFERENCE VALUES(
				:NEW.USERID,
				GEN,
				DIS,
				OCCU,
				LEV,
				INST,
				200,
				150,
				40,
				20,
				H1,
				H2,
				H3,
				H4,
				H5
		);
END;
/
